prometheus:
    image: prom/prometheus:latest
    container_name: ixnetwork_prometheus
    depends_on:
    - "grafana"
    - "ixnetwork"
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ixnetwork_node_exporter
    restart: unless-stopped
    expose:
      - 9100
  
  grafana:
    image: grafana/grafana:latest
    container_name: ixnetwork_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=ixngra.com
      # - GF_SMTP_ENABLED=true
      # - GF_SMTP_HOST=smtp.gmail.com:587
      # - GF_SMTP_USER=myadrress@gmail.com
      # - GF_SMTP_PASSWORD=mypassword
      # - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com


  ixnetwork:
    image: ixnetworkweb_9.20.2112.27_image
    container_name: ixnetwork
    restart: unless-stopped






docker run --net <bridge name> \
          --ip <container ip> \
          --hostname <hostname> \
	  --name <container name> \
	  --privileged \
	  --restart=always \
	  --cap-add=SYS_ADMIN \
          --cap-add=SYS_TIME \
          --cap-add=NET_ADMIN \
          --cap-add=SYS_PTRACE \
          -i -d \
          -v /sys/fs/cgroup:/sys/fs/cgroup \
          -v /var/crash/=/var/crash \
          -v <host configs location>:/root/.local/share/Ixia/sdmStreamManager/common \
          -v <host results location>:/root/.local/share/Ixia/IxNetwork/data/result \
          -v <host settingslocation>:/root/.local/share/IXIA/IxNetwork.Globals \
          --tmpfs /run \
          <image name>  <-- Get image name from step 4
