services:
  prometheus:
      image: prom/prometheus:latest
      container_name: ixnetwork_prometheus
      depends_on:
      - "ixnetwork"
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
        - ./data/prometheus/data:/prometheus
      command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        - '-storage.local.path=/prometheus'
        - '-alertmanager.url=http://alertmanager:9093'
      expose:
        - 9090
      ports:
        - 9090:9090
      links:
        - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ixnetwork_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  grafana:
    image: grafana/grafana:latest
    container_name: ixnetwork_grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=ixngra.com
      # - GF_SMTP_ENABLED=true
      # - GF_SMTP_HOST=smtp.gmail.com:587
      # - GF_SMTP_USER=myadrress@gmail.com
      # - GF_SMTP_PASSWORD=mypassword
      # - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com


  ixnetwork:
    image: ixnetworkweb_9.20.2112.27_image
    container_name: ixnetwork
    restart: unless-stopped
    privileged: true
    expose:
      - 11009
      - 443
    ports:
      - 11009:11009
      - 443:443
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/crash/:/var/crash
      - ./ixn:/root/.local/share/Ixia/sdmStreamManager/common
      - ./ixn:/root/.local/share/Ixia/IxNetwork/data/result
      - ./ixn:/root/.local/share/IXIA/IxNetwork.Globals
    tmpfs:
      - /run

