services:

  prometheus:
    image: prom/prometheus
    container_name: ixnetwork_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    build: ./grafana
    container_name: ixnetwork_grafana
    restart: unless-stopped
    # volumes:
    #   - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    expose:
      - 3000

  ixnetwork-app:
    build: ./ixnetwork-app
    container_name: ixnetwork_app
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    command: ["python3", "ixnetwork-app/get-publish-stats.py"]


